---
title: "symbioMap"
output: 
  html_document:
    toc: false
date: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

####

#### Interactive map of current collection (4,147 samples 01/01/23)


```{r, warning=FALSE, message=FALSE}



library(tidyverse)
library(magrittr)
library(sf)
library(leaflet)
library(httr)
```


```{r, cache=TRUE, warning=FALSE, message=FALSE, fig.width=10, fig.height=8}

collections_sf <-read.csv("https://raw.githubusercontent.com/symbiobase/symbioID/main/Symbiobase.csv")  |>
  dplyr::select(sample_id, collection_date, location, site, area, subregion, longitude, latitude, host_family, host_genus, host_species) |> 
  mutate(lat=round(latitude,3), lon=round(longitude,3)) |> 
  na.omit(longitude) |> 
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326) |> 
  mutate(location = gsub("_", " ", location),
         site = gsub("_", " ", site),
         area = gsub("_", " ", area),
         subregion = gsub("_", " ", subregion),
         host_genus = gsub("_", " ", host_genus),
         host_species = gsub("_", " ", host_species)) |> 
   mutate(gbr_region = case_when(
    lat > -16 ~ "northern Great Barrier Reef",
    lat <= -16 & lat > -25 ~ "southern Great Barrier Reef",
    lat <= -25 ~ "Sub-tropical Queensland"
  ))

regional_hulls <- collections_sf %>%
  group_by(gbr_region) %>%
  summarise(geometry = st_union(geometry)) %>%
  st_convex_hull() |> 
  st_centroid()


# link to GBR shape file:
url <- "https://data.gov.au/data/dataset/51199513-98fa-46e6-b766-8e1e1c896869/resource/01573d07-ce10-461d-9f20-86e8e6cf5893/download/data.zip"
temp_zip <- tempfile()
invisible(capture.output(GET(url, write_disk(temp_zip, overwrite = TRUE))))
temp_dir <- tempdir()
unzip(temp_zip, exdir = temp_dir)
shapefiles <- list.files(temp_dir, pattern = "\\.shp$", recursive=TRUE, full.names = TRUE)
shapefile_path <- shapefiles[1]

# extract and tidy to sf
gbr_shape <- st_read(shapefile_path, quiet=TRUE) %>%
  mutate(longitude = st_drop_geometry(.)$X_COORD,
         latitude = st_drop_geometry(.)$Y_COORD) |>
  filter(FEAT_NAME=="Reef") |>
  st_set_crs(4283) |>
  st_transform(4326) |>
  st_make_valid() |> 
  clean_names() |> 
  dplyr::select(loc_name_s, qld_name, gbr_name, label_id, geometry, longitude, latitude) |> 
  mutate(Reef.Name = as.factor(gbr_name)) |> 
  mutate(GBRMPA.id = as.factor(label_id)) |> 
  mutate(id=sub("([a-zA-Z])$", "", label_id)) 



collections_sf <- read.csv("https://raw.githubusercontent.com/symbiobase/symbioID/main/Symbiobase.csv") |>
  dplyr::select(sample_id, collection_date, location, site, area, subregion, longitude, latitude, host_family, host_genus, host_species) |> 
  mutate(lat=round(latitude,3), lon=round(longitude,3)) |> 
  na.omit(longitude) |> 
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326) |> 
  mutate(location = gsub("_", " ", location),
         site = gsub("_", " ", site),
         area = gsub("_", " ", area),
         subregion = gsub("_", " ", subregion),
         host_genus = gsub("_", " ", host_genus),
         host_species = gsub("_", " ", host_species)) |> 
   mutate(gbr_region = case_when(
    lat > -16 ~ "northern Great Barrier Reef",
    lat <= -16 & lat > -25 ~ "southern Great Barrier Reef",
    lat <= -25 ~ "Sub-tropical Queensland"
  ))

```

### Host Genera {.tabset}
 
#### All Taxa

```{r, cache=TRUE, warning=FALSE, message=FALSE, fig.width=10, fig.height=8}

color_mapping <- c(
  "Acroporidae" = "lightblue",
  "Merulinidae" = "pink",
  "Dendrophylliidae" = "purple",
  "Pocilloporidae" = "green",
  "Poritidae" = "orange",
  "Mussidae" = "darkred",
  "Sarcophytidae" = "beige",
  "Sinulariidae" = "cadetblue",
  "Faviidae" = "lightred",
  "Xeniidae" = "gray"
)

# Function to get the marker color based on host family
getMarkerColor <- function(host_family) {
  color_mapping[host_family]
}

# Add colors to collections_sf data
collections_sf$marker_color <- sapply(collections_sf$host_family, getMarkerColor)



icons <- awesomeIcons(
  icon = 'ios-close',
  iconColor = 'black',
  library = 'ion',
  markerColor = as.character(collections_sf$marker_color)
)

leaflet() %>%
  addProviderTiles("Esri.WorldImagery") %>%
  addPolygons(data=gbr_shape,
    color = "white",
    weight = 1,
    opacity = 0.2,
    fill = "white",
    popup = ~paste("Reef Name: ", as.character(Reef.Name), "<br>", "GBRMPA ID: ", as.character(GBRMPA.id)),
    label =  ~paste(as.character(Reef.Name), "(", as.character(GBRMPA.id), ")"),
  ) %>%
   addLabelOnlyMarkers(
    data = regional_hulls,
    label = ~gbr_region,
    labelOptions = labelOptions(
      noHide = TRUE,
      direction = "right",
      offset = c(20, 0),  # x offset, no y offset
      textOnly = TRUE,    # removes label outline and fill
      style = list("color" = "white") # Optional: change label text color
    )
  ) %>%
   addAwesomeMarkers(
    data = collections_sf,
    icon = icons,
    clusterOptions = markerClusterOptions(),
    popup = ~paste("Sample ID:", sample_id,
                   "<br>Location:", location,
                   "<br>Site:", site,
                   "<br>Host family:", host_family,
                   "<br>Host genus:", host_genus,
                   "<br>Host species:", host_species),
    label = ~as.character(sample_id)
  )

```

#### Acropora

```{r, cache=TRUE, warning=FALSE, message=FALSE, fig.width=10, fig.height=8}



leaflet() %>%
  addProviderTiles("Esri.WorldImagery") %>%
  addPolygons(data=gbr_shape,
    color = "white",
    weight = 1,
    opacity = 0.2,
    fill = "white",
    popup = ~paste("Reef Name: ", as.character(Reef.Name), "<br>", "GBRMPA ID: ", as.character(GBRMPA.id)),
    label =  ~paste(as.character(Reef.Name), "(", as.character(GBRMPA.id), ")"),
  ) %>%
   addLabelOnlyMarkers(
    data = regional_hulls,
    label = ~gbr_region,
    labelOptions = labelOptions(
      noHide = TRUE,
      direction = "right",
      offset = c(20, 0),  # x offset, no y offset
      textOnly = TRUE,    # removes label outline and fill
      style = list("color" = "white") # Optional: change label text color
    )
  ) %>%
  addMarkers(data = collections_sf |> filter(host_genus=="Acropora"), 
             clusterOptions = markerClusterOptions(), 
             popup = ~paste("Sample ID:", sample_id, 
                            "<br>Location:", location, 
                            "<br>Site:", site, 
                            "<br>Host family:", host_family,
                            "<br>Host genus:", host_genus,
                            "<br>Host species:", host_species), label = ~as.character(sample_id))

```

#### Acanthastraea

```{r, cache=TRUE, warning=FALSE, message=FALSE, fig.width=10, fig.height=8}


leaflet() %>%
  addProviderTiles("Esri.WorldImagery") %>%
  addPolygons(data=gbr_shape,
    color = "white",
    weight = 1,
    opacity = 0.2,
    fill = "white",
    popup = ~paste("Reef Name: ", as.character(Reef.Name), "<br>", "GBRMPA ID: ", as.character(GBRMPA.id)),
    label =  ~paste(as.character(Reef.Name), "(", as.character(GBRMPA.id), ")"),
  ) %>%
    addLabelOnlyMarkers(
    data = regional_hulls,
    label = ~gbr_region,
    labelOptions = labelOptions(
      noHide = TRUE,
      direction = "right",
      offset = c(20, 0),  # x offset, no y offset
      textOnly = TRUE,    # removes label outline and fill
      style = list("color" = "white") # Optional: change label text color
    )
  ) %>%
  addMarkers(data = collections_sf |> filter(host_genus=="Acanthastrea"), 
             clusterOptions = markerClusterOptions(), 
             popup = ~paste("Sample ID:", sample_id, 
                            "<br>Location:", location, 
                            "<br>Site:", site, 
                            "<br>Host family:", host_family,
                            "<br>Host genus:", host_genus,
                            "<br>Host species:", host_species), label = ~as.character(sample_id))

```


#### Turbinaria

```{r, cache=TRUE, warning=FALSE, message=FALSE, fig.width=10, fig.height=8}


leaflet() %>%
  addProviderTiles("Esri.WorldImagery") %>%
  addPolygons(data=gbr_shape,
    color = "white",
    weight = 1,
    opacity = 0.2,
    fill = "white",
    popup = ~paste("Reef Name: ", as.character(Reef.Name), "<br>", "GBRMPA ID: ", as.character(GBRMPA.id)),
    label =  ~paste(as.character(Reef.Name), "(", as.character(GBRMPA.id), ")"),
  ) %>%
   addLabelOnlyMarkers(
    data = regional_hulls,
    label = ~gbr_region,
    labelOptions = labelOptions(
      noHide = TRUE,
      direction = "right",
      offset = c(20, 0),  # x offset, no y offset
      textOnly = TRUE,    # removes label outline and fill
      style = list("color" = "white") # Optional: change label text color
    )
  ) %>%
  addMarkers(data = collections_sf |> filter(host_genus=="Turbinaria"), 
             clusterOptions = markerClusterOptions(), 
             popup = ~paste("Sample ID:", sample_id, 
                            "<br>Location:", location, 
                            "<br>Site:", site, 
                            "<br>Host family:", host_family,
                            "<br>Host genus:", host_genus,
                            "<br>Host species:", host_species), label = ~as.character(sample_id))

```
